services:
  otpservice:
    image: otp-service:0.0.0
    container_name: otp-service
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5254:5254
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - REDIS_ENDPOINT=redis
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
      - ./data/appsettings.json:/app/appsettings.json:ro
      - ./data/appsettings.Development.json:/app/appsettings.Development.json:ro
      - ./.env:/app/.env:ro
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
